# Generated by Django 4.0.3 on 2022-08-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=0)),
                ('residence_actuelle', models.CharField(max_length=50)),
                ('Commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Zone', models.CharField(max_length=50)),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membre')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='Province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province'),
        ),
        migrations.AddField(
            model_name='membre',
            name='Zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=50)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membre')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.province'),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
                ('Membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membre')),
                ('Province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province')),
                ('Zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
    ]
