# Generated by Django 4.0.3 on 2022-08-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remboursement',
            name='membre',
        ),
        migrations.AddField(
            model_name='remboursement',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.credit'),
        ),
    ]
