# Generated by Django 4.0.3 on 2022-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_remboursement_membre_remboursement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
