# Generated by Django 4.0.3 on 2022-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membre_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='CNI',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
