# Generated by Django 4.0.3 on 2022-09-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_membre_cni_membre_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
