# Generated by Django 4.0.3 on 2022-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_membre_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='etat_civil',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=50, null=True),
        ),
    ]
