# Generated by Django 4.0.3 on 2022-09-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_membre_etat_civil_membre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='etat_civil',
            field=models.CharField(choices=[('Celibataire', 'Celibataire'), ('Marie', 'Marie')], max_length=50, null=True),
        ),
    ]
