# Generated by Django 4.0.3 on 2022-09-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_membre_etat_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='etat_civil',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='genre',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Communique',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.membre')),
            ],
        ),
    ]
